- id: 1x
  cpu: 1000m
  guaranteed_cpu: 1000m
  memory: 1500Mi
- id: 2x
  cpu: 2000m
  guaranteed_cpu: 2000m
  memory: 3000Mi
- id: 4x
  cpu: 4000m
  guaranteed_cpu: 4000m
  memory: 6000Mi
- id: 1x.standard
  cpu: 1000m
  guaranteed_cpu: 250m
  memory: 500Mi
- id: 2x.standard
  cpu: 2000m
  guaranteed_cpu: 500m
  memory: 1000Mi
- id: 4x.standard
  cpu: 4000m
  guaranteed_cpu: 1000m
  memory: 2000Mi
- id: 8x.standard
  cpu: 8000m
  guaranteed_cpu: 2000m
  memory: 4000Mi
- id: 1x.performance
  cpu: 1000m
  guaranteed_cpu: 1000m
  memory: 1500Mi
- id: 2x.performance
  cpu: 2000m
  guaranteed_cpu: 2000m
  memory: 3000Mi
- id: 4x.performance
  cpu: 4000m
  guaranteed_cpu: 4000m
  memory: 6000Mi
- id: 8x.performance
  cpu: 8000m
  guaranteed_cpu: 8000m
  memory: 12000Mi
